[[pages]]
name = "PULSE"
icon = ""
is_section = true


[[pages]]
path = "pages/referendum.py"
name = "Polling"
icon = ":white_medium_small_square:"

[[pages]]
path = "pages/results.py"
name = "Results"
icon = ":white_medium_small_square:"

[[pages]]
path = "pages/explorer.py"
name = "Explorer"
icon = ":white_medium_small_square:"
