V_PCT = 0.2  # vocabulary slice percentage
MIN_P = 0.99 # minimum cumulative probability for completion analysis

[connections.vllm]
batch_size = 8 # No. of requests to batch together (if the API supports batching)
token = "EMPTY"
